INSERT INTO product (id, version, created, name, firm, productVersion, productType) VALUES
                                                                                        (gen_random_uuid(), 1, NOW(), 'QLED TV', 'Samsung', 'Q80T', 'HOME_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'OLED TV', 'LG', 'CX Series', 'HOME_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), '4K TV', 'Sony', 'X950H', 'HOME_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Microwave Oven', 'Panasonic', 'NN-SN966S', 'KITCHEN_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Refrigerator', 'Whirlpool', 'WRX735SDHZ', 'KITCHEN_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Washing Machine', 'Bosch', 'WAT28400UC', 'HOME_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'iPhone 13', 'Apple', 'A2483', 'SMARTPHONES'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Galaxy S21', 'Samsung', 'SM-G991U', 'SMARTPHONES'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Pixel 6', 'Google', 'GA01341-US', 'SMARTPHONES'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'MacBook Pro', 'Apple', 'A2338', 'COMPUTERS'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Surface Laptop', 'Microsoft', '1950', 'COMPUTERS'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'ThinkPad', 'Lenovo', 'X1 Carbon Gen 9', 'COMPUTERS'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Dishwasher', 'Bosch', 'SHXM78Z55N', 'KITCHEN_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Vacuum Cleaner', 'Dyson', 'V11 Torque Drive', 'HOME_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Air Conditioner', 'Daikin', 'FTKM35TV16W', 'HOME_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Blender', 'Philips', 'HR3652/01', 'KITCHEN_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Smartwatch', 'Garmin', 'Fenix 6', 'SMARTPHONES'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Gaming PC', 'Alienware', 'Aurora R11', 'COMPUTERS'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Home Theater System', 'Yamaha', 'YHT-4950U', 'HOME_APPLIANCE'),
                                                                                        (gen_random_uuid(), 1, NOW(), 'Espresso Machine', 'Breville', 'BES870XL', 'KITCHEN_APPLIANCE');