INSERT INTO product (id, name, firm, product_version, product_type, version, created) VALUES
--                                                                                         (gen_random_uuid(), 1, NOW(), 'QLED TV', 'Samsung', 'Q80T', 'HOME_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'OLED TV', 'LG', 'CX Series', 'HOME_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), '4K TV', 'Sony', 'X950H', 'HOME_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Microwave Oven', 'Panasonic', 'NN-SN966S', 'KITCHEN_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Refrigerator', 'Whirlpool', 'WRX735SDHZ', 'KITCHEN_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Washing Machine', 'Bosch', 'WAT28400UC', 'HOME_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'iPhone 13', 'Apple', 'A2483', 'SMARTPHONES'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Galaxy S21', 'Samsung', 'SM-G991U', 'SMARTPHONES'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Pixel 6', 'Google', 'GA01341-US', 'SMARTPHONES'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'MacBook Pro', 'Apple', 'A2338', 'COMPUTERS'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Surface Laptop', 'Microsoft', '1950', 'COMPUTERS'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'ThinkPad', 'Lenovo', 'X1 Carbon Gen 9', 'COMPUTERS'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Dishwasher', 'Bosch', 'SHXM78Z55N', 'KITCHEN_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Vacuum Cleaner', 'Dyson', 'V11 Torque Drive', 'HOME_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Air Conditioner', 'Daikin', 'FTKM35TV16W', 'HOME_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Blender', 'Philips', 'HR3652/01', 'KITCHEN_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Smartwatch', 'Garmin', 'Fenix 6', 'SMARTPHONES'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Gaming PC', 'Alienware', 'Aurora R11', 'COMPUTERS'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Home Theater System', 'Yamaha', 'YHT-4950U', 'HOME_APPLIANCE'),
--                                                                                         (gen_random_uuid(), 1, NOW(), 'Espresso Machine', 'Breville', 'BES870XL', 'KITCHEN_APPLIANCE'),

                                                                                        (gen_random_uuid(), 'iPhone 13', 'Apple', '13', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Galaxy S21', 'Samsung', 'S21', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'MacBook Air', 'Apple', 'M1', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'ThinkPad X1 Carbon', 'Lenovo', 'Gen 9', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Dyson V11', 'Dyson', 'V11', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Roomba i7', 'iRobot', 'i7', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Instant Pot Duo', 'Instant Pot', 'Duo', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Vitamix 5200', 'Vitamix', '5200', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Dell XPS 13', 'Dell', '9310', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Surface Pro 7', 'Microsoft', 'Pro 7', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'OnePlus 9', 'OnePlus', '9', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Pixel 6', 'Google', '6', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'PS5', 'Sony', 'PlayStation 5', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'AirPods Pro', 'Apple', 'Pro', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'KitchenAid Mixer', 'KitchenAid', 'Artisan', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Ninja Blender', 'Ninja', 'BL770', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'HP Spectre x360', 'HP', 'x360', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Asus ROG Strix', 'Asus', 'G15', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Galaxy Tab S7', 'Samsung', 'S7', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'iPad Pro', 'Apple', 'M1', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Sony Bravia X90J', 'Sony', 'X90J', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'LG OLED CX', 'LG', 'CX', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Bose QuietComfort 35', 'Bose', '35', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Jabra Elite 75t', 'Jabra', '75t', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Breville Barista Express', 'Breville', 'Express', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Cuisinart Coffee Maker', 'Cuisinart', 'DCC-3200', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Nest Thermostat', 'Google', 'Thermostat', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Ring Doorbell', 'Ring', '3', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Eufy RoboVac 11S', 'Eufy', '11S', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'TP-Link Archer A7', 'TP-Link', 'A7', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Amazon Echo Dot', 'Amazon', '4th Gen', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Sony WH-1000XM4', 'Sony', 'XM4', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Google Nest Hub', 'Google', 'Hub', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Logitech MX Master 3', 'Logitech', 'Master 3', 'COMPUTERS', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Canon EOS R5', 'Canon', 'R5', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Nikon Z6 II', 'Nikon', 'Z6 II', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Brother HL-L2395DW', 'Brother', '2395DW', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'KitchenAid Toaster', 'KitchenAid', 'KMT4116CU', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Hamilton Beach Microwave', 'Hamilton Beach', 'P100N30ALS3A', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Anova Sous Vide', 'Anova', 'Nano', 'KITCHEN_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Apple Watch Series 6', 'Apple', 'Series 6', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Samsung Galaxy Watch 4', 'Samsung', 'Watch 4', 'HOME_APPLIANCE', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Huawei P40 Pro', 'Huawei', 'P40 Pro', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'LG Wing', 'LG', 'Wing', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Xiaomi Mi 11', 'Xiaomi', '11', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Realme GT', 'Realme', 'GT', 'SMARTPHONES', 1, NOW()),
                                                                                        (gen_random_uuid(), 'Oppo Find X3', 'Oppo', 'X3', 'SMARTPHONES', 1, NOW());